CREATE TABLE reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    analysis_id BIGINT NOT NULL,

    -- Records when this particular report record was generated.
    generated_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_reports
        PRIMARY KEY (report_id),

    -- A report has no independent meaning after its parent analysis job is
    -- explicitly deleted, so it is removed with that analysis.
    CONSTRAINT fk_reports_analysis
        FOREIGN KEY (analysis_id)
        REFERENCES analysis_jobs(analysis_id)
        ON DELETE CASCADE
);

-- Supports retrieving reports for one analysis job, newest report first.
-- Its analysis_id prefix also supports foreign-key lookup operations.
CREATE INDEX idx_reports_analysis_generated_at
    ON reports (analysis_id, generated_at DESC);
