CREATE TABLE class_metrics (
    class_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Metrics belong directly to the analysis execution that produced them.
    analysis_job_id BIGINT NOT NULL,

    class_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,

    -- Source-code location and size metrics
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    loc INTEGER NOT NULL,
    number_of_lines_of_code INTEGER NOT NULL,

    -- Object-oriented / structural metrics
    -- DOUBLE PRECISION preserves fractional analyzer values without imposing
    -- an artificial fixed decimal scale on computed measurements.
    cyclomatic_complexity DOUBLE PRECISION NOT NULL,
    dit INTEGER NOT NULL,
    cbo INTEGER NOT NULL,
    fan_in INTEGER NOT NULL,
    fan_out INTEGER NOT NULL,
    lcom DOUBLE PRECISION NOT NULL,
    noc INTEGER NOT NULL,
    rfc INTEGER NOT NULL,
    wmc DOUBLE PRECISION NOT NULL,

    -- Visibility/member-count metrics
    number_of_attributes INTEGER NOT NULL,
    number_of_methods INTEGER NOT NULL,
    number_of_private_attributes INTEGER NOT NULL,
    number_of_private_methods INTEGER NOT NULL,
    number_of_public_attributes INTEGER NOT NULL,
    number_of_public_methods INTEGER NOT NULL,

    -- Git history and churn metrics
    number_of_versions_until INTEGER NOT NULL,
    number_of_authors_until INTEGER NOT NULL,
    lines_added_until INTEGER NOT NULL,
    max_lines_added_until INTEGER NOT NULL,
    avg_lines_added_until DOUBLE PRECISION NOT NULL,
    lines_removed_until INTEGER NOT NULL,
    max_lines_removed_until INTEGER NOT NULL,
    avg_lines_removed_until DOUBLE PRECISION NOT NULL,
    code_churn_until INTEGER NOT NULL,
    max_code_churn_until INTEGER NOT NULL,
    avg_code_churn_until DOUBLE PRECISION NOT NULL,
    age_with_respect_to DOUBLE PRECISION NOT NULL,
    weighted_age_with_respect_to DOUBLE PRECISION NOT NULL,

    CONSTRAINT pk_class_metrics
        PRIMARY KEY (class_id),

    -- Prevents duplicate storage of the same analyzed class region while still
    -- allowing repeated/local class names at different source locations.
    CONSTRAINT uk_class_metrics_analysis_file_line_class
        UNIQUE (
            analysis_job_id,
            file_path,
            start_line,
            class_name
        ),

    -- Generated metrics have no independent meaning after their analysis job
    -- is explicitly deleted.
    CONSTRAINT fk_class_metrics_analysis_job
        FOREIGN KEY (analysis_job_id)
        REFERENCES analysis_jobs(analysis_id)
        ON DELETE CASCADE
);

-- No separate analysis_job_id index is needed. The unique constraint creates
-- an index beginning with analysis_job_id and file_path, supporting analysis
-- lookups and stable per-file class ordering.
