CREATE TABLE class_comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Identifies the analyzed class/file that contained the raw comment.
    class_id BIGINT NOT NULL,

    -- Stores complete extracted comment text. A comment is not automatically SATD.
    comment TEXT NOT NULL,

    CONSTRAINT pk_class_comments
        PRIMARY KEY (comment_id),

    -- Extracted comments have no independent meaning after their Class_Metrics
    -- parent is removed, so they are deleted with that parent.
    CONSTRAINT fk_class_comments_class_metrics
        FOREIGN KEY (class_id)
        REFERENCES class_metrics(class_id)
        ON DELETE CASCADE
);

-- Supports retrieving all comments for one class and class-metrics foreign-key
-- deletion operations. Comment text itself is intentionally not indexed.
CREATE INDEX idx_class_comments_class_id
    ON class_comments (class_id);
