CREATE TABLE satd_detections (
    detection_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Identifies the raw extracted comment classified by the ML model.
    comment_id BIGINT NOT NULL,

    -- Stores the classification label without guessing a fixed taxonomy.
    category VARCHAR(100) NOT NULL,

    -- Normalized ML confidence: 0.0 is lowest and 1.0 is highest.
    confidence_score DOUBLE PRECISION NOT NULL,

    CONSTRAINT pk_satd_detections
        PRIMARY KEY (detection_id),

    -- Stores at most one current authoritative classification per comment.
    CONSTRAINT uk_satd_detections_comment_id
        UNIQUE (comment_id),

    -- Rejects confidence values outside the normalized 0.0–1.0 range.
    CONSTRAINT ck_satd_detections_confidence_score
        CHECK (
            confidence_score >= 0.0
            AND confidence_score <= 1.0
        ),

    -- A classification has no meaning after its raw source comment is removed,
    -- so it is deleted together with that comment.
    CONSTRAINT fk_satd_detections_class_comment
        FOREIGN KEY (comment_id)
        REFERENCES class_comments(comment_id)
        ON DELETE CASCADE
);

-- No separate comment_id index is needed because the UNIQUE constraint creates
-- an index supporting classification lookup and foreign-key operations.
