CREATE TABLE debt_scores (
    debt_score_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Identifies the analyzed class receiving this derived assessment.
    class_id BIGINT NOT NULL,

    -- Computed debt score. Its formula and valid range are intentionally left
    -- to future analysis and reporting business logic.
    technical_debt_score DOUBLE PRECISION NOT NULL,

    -- String classifications remain unconstrained until their authoritative
    -- health and risk taxonomies are finalized.
    health_score VARCHAR(100) NOT NULL,
    risk_level VARCHAR(100) NOT NULL,

    CONSTRAINT pk_debt_scores
        PRIMARY KEY (debt_score_id),

    -- Stores one current authoritative debt assessment per analyzed class.
    CONSTRAINT uk_debt_scores_class_id
        UNIQUE (class_id),

    -- A derived assessment has no meaning after its Class_Metrics parent is
    -- removed, so it is deleted together with that parent.
    CONSTRAINT fk_debt_scores_class_metrics
        FOREIGN KEY (class_id)
        REFERENCES class_metrics(class_id)
        ON DELETE CASCADE
);

-- No separate class_id index is needed because the UNIQUE constraint creates
-- an index supporting assessment lookup and foreign-key operations.
