CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    auth0_user_id VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    github_username VARCHAR(255) NOT NULL,

    email_verified BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users
        PRIMARY KEY (user_id),

    CONSTRAINT uk_users_auth0_user_id
        UNIQUE (auth0_user_id),

    CONSTRAINT uk_users_email
        UNIQUE (email),

    CONSTRAINT uk_users_github_username
        UNIQUE (github_username)
);
