CREATE TABLE companies (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    company_name VARCHAR(255) NOT NULL,
    github_organization_url VARCHAR(255) NOT NULL,

    created_by BIGINT NOT NULL,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_companies
        PRIMARY KEY (company_id),

    CONSTRAINT uk_companies_github_organization_url
        UNIQUE (github_organization_url),

    CONSTRAINT fk_companies_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_companies_created_by
    ON companies (created_by);
