CREATE TABLE super_admins (
    super_admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_super_admins
        PRIMARY KEY (super_admin_id),

    CONSTRAINT uk_super_admins_user_company
        UNIQUE (user_id, company_id),

    CONSTRAINT fk_super_admins_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_super_admins_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_super_admins_company_id
    ON super_admins (company_id);
