CREATE TABLE repositories (
    repository_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    company_id BIGINT NOT NULL,

    github_repository_id VARCHAR(255) NOT NULL,
    repository_name VARCHAR(255) NOT NULL,
    repository_url VARCHAR(255) NOT NULL,
    default_branch VARCHAR(255),

    created_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_repositories
        PRIMARY KEY (repository_id),

    CONSTRAINT uk_repositories_github_repository_id
        UNIQUE (github_repository_id),

    CONSTRAINT uk_repositories_repository_url
        UNIQUE (repository_url),

    CONSTRAINT fk_repositories_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_repositories_company_id
    ON repositories (company_id);
