CREATE TABLE members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    assigned_by BIGINT NOT NULL,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_members
        PRIMARY KEY (member_id),

    CONSTRAINT uk_members_user_company
        UNIQUE (user_id, company_id),

    CONSTRAINT fk_members_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_members_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_members_assigned_by
        FOREIGN KEY (assigned_by)
        REFERENCES users(user_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_members_company_id
    ON members (company_id);

CREATE INDEX idx_members_assigned_by
    ON members (assigned_by);
