CREATE TABLE invitations (
    invitation_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    email VARCHAR(255) NOT NULL,

    repository_id BIGINT NOT NULL,
    super_admin_id BIGINT NOT NULL,

    -- A unique opaque token identifies a single invitation link.
    token VARCHAR(255) NOT NULL,

    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',

    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_invitations
        PRIMARY KEY (invitation_id),

    CONSTRAINT uk_invitations_token
        UNIQUE (token),

    -- Keeps stored string values aligned with the Java InvitationStatus enum.
    CONSTRAINT ck_invitations_status
        CHECK (
            status IN (
                'PENDING',
                'ACCEPTED',
                'REJECTED',
                'EXPIRED'
            )
        ),

    -- An invitation has no useful purpose after its repository is deleted.
    CONSTRAINT fk_invitations_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories(repository_id)
        ON DELETE CASCADE,

    -- Preserve invitation history when an admin assignment is still referenced.
    CONSTRAINT fk_invitations_super_admin
        FOREIGN KEY (super_admin_id)
        REFERENCES super_admins(super_admin_id)
        ON DELETE NO ACTION
);

-- Only one active PENDING invitation may exist for the same
-- email/repository pair. Historical resolved invitations remain allowed.
CREATE UNIQUE INDEX uk_invitations_pending_email_repository
    ON invitations (email, repository_id)
    WHERE status = 'PENDING';

CREATE INDEX idx_invitations_repository_id
    ON invitations (repository_id);

-- Supports both all-invitation and status-filtered queries for an admin.
CREATE INDEX idx_invitations_super_admin_status
    ON invitations (super_admin_id, status);

CREATE INDEX idx_invitations_email
    ON invitations (email);

-- Future expiration processing only needs unresolved invitations.
CREATE INDEX idx_invitations_pending_expires_at
    ON invitations (expires_at)
    WHERE status = 'PENDING';
