CREATE TABLE analysis_jobs (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    repository_id BIGINT NOT NULL,
    started_by BIGINT NOT NULL,

    status VARCHAR(50) NOT NULL DEFAULT 'QUEUED',

    started_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Null while queued/running; future service or worker-result handling sets
    -- it when the job reaches a terminal state.
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT pk_analysis_jobs
        PRIMARY KEY (analysis_id),

    -- Keeps stored string values aligned with the Java AnalysisJobStatus enum.
    CONSTRAINT ck_analysis_jobs_status
        CHECK (
            status IN (
                'QUEUED',
                'RUNNING',
                'COMPLETED',
                'FAILED',
                'CANCELLED'
            )
        ),

    -- Analysis history is valuable data, so repository deletion must be
    -- explicit rather than silently cascading through completed jobs.
    CONSTRAINT fk_analysis_jobs_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories(repository_id)
        ON DELETE RESTRICT,

    -- Preserve who requested an analysis and prevent loss of audit attribution.
    CONSTRAINT fk_analysis_jobs_started_by
        FOREIGN KEY (started_by)
        REFERENCES users(user_id)
        ON DELETE RESTRICT
);

-- Supports repository analysis history and repository foreign-key operations.
CREATE INDEX idx_analysis_jobs_repository_started_at
    ON analysis_jobs (repository_id, started_at DESC);

-- Supports user analysis history and user foreign-key operations.
CREATE INDEX idx_analysis_jobs_started_by_started_at
    ON analysis_jobs (started_by, started_at DESC);

-- Supports operational queries for queued, running, failed, or completed jobs.
CREATE INDEX idx_analysis_jobs_status_started_at
    ON analysis_jobs (status, started_at);
