CREATE TABLE analysis_status_history (
    status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    analysis_id BIGINT NOT NULL,

    status VARCHAR(50) NOT NULL,

    -- Optional context for progress, failures, cancellation, or worker events.
    message TEXT,

    -- Records when the lifecycle event occurred.
    timestamp TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_analysis_status_history
        PRIMARY KEY (status_history_id),

    -- Keeps historical values aligned with AnalysisJobStatus and V8.
    CONSTRAINT ck_analysis_status_history_status
        CHECK (
            status IN (
                'QUEUED',
                'RUNNING',
                'COMPLETED',
                'FAILED',
                'CANCELLED'
            )
        ),

    -- History has no independent meaning after its analysis job is explicitly
    -- deleted, so dependent lifecycle events are removed with their parent.
    CONSTRAINT fk_analysis_status_history_analysis
        FOREIGN KEY (analysis_id)
        REFERENCES analysis_jobs(analysis_id)
        ON DELETE CASCADE
);

-- Supports chronological lifecycle-history retrieval for one analysis job.
-- Its analysis_id prefix also supports foreign-key lookup operations.
CREATE INDEX idx_analysis_status_history_analysis_timestamp
    ON analysis_status_history (analysis_id, timestamp);
